backbone: "yolox_darknet53" #option for backbone, you can choose 'yolox_darknet53' or 'yolox_x'
device_target: "GPU"
# ======================================================
# Train option
save_graphs: False
lr_scheduler: "yolox_warm_cos_lr"
max_epoch: 1
total_epoch: 2
data_dir: "/home/psy/workplace/datasets/coco2017"
# last no data aug related
yolox_no_aug_ckpt: ""
need_profiler: 0
pretrained: ''
resume_yolox: ''

# data aug
data_aug: True
flip_prob: 0.5
hsv_prob: 1.0
# ========================================================\
# dataset related
per_batch_size: 4

# network configuration
depth_wise: False
max_gt: 120
num_classes: 80
#input_size: [640, 640]
input_size: [512, 512]
fpn_strides: [8, 16, 32]
use_l1: False
use_syc_bn: True
updates: 0.0

# dynamic_k
n_candidate_k: 10

# optimizer and lr related
lr: 0.0001 # 0.04 for yolox-x
min_lr_ratio: 0.001
warmup_epochs: 5
weight_decay: 0.0005
momentum: 0.9
no_aug_epochs: 15
# logging related
log_interval: 30
ckpt_interval: -1
is_save_on_master: 1
ckpt_max_num: 60
opt: "Momentum"

# distributed related
is_distributed: 0   # change by lxy 9-21
rank: 0
group_size: 1
bind_cpu: True
device_num: 8

# modelart
is_modelArts: 0
enable_modelarts: False

need_modelarts_dataset_unzip: False
modelarts_dataset_unzip_name: "coco2017"

data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/home/work/user-job-dir/inputs/data/coco2017"
output_path: "./"
load_path: "/cache/checkpoint_path"
ckpt_path: './'

# Eval option
log_path: "val/outputs/"
val_ckpt: "save/yolox/yolox_1-10_1250.ckpt"
conf_thre: 0.001
nms_thre: 0.65
eval_interval: 10
run_eval: False

# export option
file_format: 'MINDIR'
export_bs: 1
